apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
data:
  DEVTRON_URL: "https://<devtron_url>/orchestrator/app/ci-pipeline/trigger"
  DEVTRON_VERIFY_SSL: "false"
  REST_REQ_BODY: |
    {
      "pipelineId": <ciPipelineId>,
      "ciPipelineMaterials": [
        {
          "Id": <ciPipelineMaterialsId>,
          "GitCommit": {
            "Commit": "<GitCommitId>"
          }
        }
      ],
      "invalidateCache": false,
      "pipelineType": "CI_BUILD",
      "runtimeParams": {
        "runtimePluginVariables": []
      }
    }
